-- This module is the root of the AndreOortConjectureCanonicalLaneLean Lean proof package.
import AndreOortConjectureCanonicalLaneLean.Basic
import AndreOortConjectureCanonicalLaneLean.SourcePackage
import AndreOortConjectureCanonicalLaneLean.SourceDependencies
import AndreOortConjectureCanonicalLaneLean.Formalization
import AndreOortConjectureCanonicalLaneLean.ReviewerBridge
import AndreOortConjectureCanonicalLaneLean.TheoremStatement
import AndreOortConjectureCanonicalLaneLean.MathlibObjects
import AndreOortConjectureCanonicalLaneLean.AdmissibleClass
import AndreOortConjectureCanonicalLaneLean.Projection
import AndreOortConjectureCanonicalLaneLean.BridgeLemmas
import AndreOortConjectureCanonicalLaneLean.GateLemmas
import AndreOortConjectureCanonicalLaneLean.FinalTheorem
import AndreOortConjectureCanonicalLaneLean.MathlibStatement
